# Generated by Django 2.0.7 on 2018-11-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('position_in_menu', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Título Numeral',
                'verbose_name_plural': 'Títulos Numerales',
                'ordering': ['position_in_menu'],
            },
        ),
    ]
