# Generated by Django 2.0.7 on 2018-11-20 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numerals', '0002_numeral_subnumeral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnumeral',
            name='numeral',
        ),
        migrations.DeleteModel(
            name='SubNumeral',
        ),
    ]
